# documentation: https://help.github.com/en/articles/workflow-syntax-for-github-actions
name: Tests relying on having EESSI pilot repo mounted
on: [push, pull_request, workflow_dispatch]
permissions:
  contents: read # to fetch code (actions/checkout)
jobs:
  pilot:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        EESSI_VERSION:
        - 2023.06
        EESSI_SOFTWARE_SUBDIR:
        - aarch64/generic
        - x86_64/amd/zen2
        - x86_64/intel/broadwell
#        - x86_64/intel/cascadelake
        - x86_64/intel/skylake_avx512
#        - x86_64/generic
        EASYSTACK_FILE:
        - eessi-2023.06-eb-4.7.2-2021a.yml
        - eessi-2023.06-eb-4.7.2-2021b.yml
        - eessi-2023.06-eb-4.7.2-2022a.yml
        - eessi-2023.06-eb-4.7.2-2022b.yml
        - eessi-2023.06-eb-4.7.2-system.yml
        - eessi-2023.06-eb-4.8.0-system.yml
        - eessi-2023.06-eb-4.8.1-2022a.yml
        - eessi-2023.06-eb-4.8.1-system.yml
    steps:
        - name: Check out software-layer repository
          uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # v3.1.0

        - name: Mount EESSI CernVM-FS pilot repository
          uses: cvmfs-contrib/github-action-cvmfs@d4641d0d591c9a5c3be23835ced2fb648b44c04b # v3.1
          with:
              cvmfs_config_package: https://github.com/NorESSI/filesystem-layer/releases/download/latest/cvmfs-config-nessi_latest_all.deb
              cvmfs_http_proxy: DIRECT
              cvmfs_repositories: pilot.nessi.no

        - name: Test check_missing_installations.sh script with EESSI_SOFTWARE_SUBDIR_OVERRIDE
          if: '!cancelled()'
          run: |
              export EESSI_SOFTWARE_SUBDIR_OVERRIDE=${{matrix.EESSI_SOFTWARE_SUBDIR}}
              source /cvmfs/pilot.nessi.no/versions/${{matrix.EESSI_VERSION}}/init/bash
              module load EasyBuild
              eb --version
              export EESSI_PREFIX=/cvmfs/pilot.nessi.no/versions/${{matrix.EESSI_VERSION}}
              export EESSI_OS_TYPE=linux
              env | grep ^EESSI | sort
              echo "just run check_missing_installations.sh (should use ${{matrix.EASYSTACK_FILE}})"
              ./check_missing_installations.sh ${{matrix.EASYSTACK_FILE}}

        - name: Test check_missing_installations.sh script without EESSI_SOFTWARE_SUBDIR_OVERRIDE
          if: '!cancelled()'
          run: |
              source /cvmfs/pilot.nessi.no/versions/${{matrix.EESSI_VERSION}}/init/bash
              module load EasyBuild
              eb --version
              export EESSI_PREFIX=/cvmfs/pilot.nessi.no/versions/${{matrix.EESSI_VERSION}}
              export EESSI_OS_TYPE=linux
              export EESSI_SOFTWARE_SUBDIR=${{matrix.EESSI_SOFTWARE_SUBDIR}}
              env | grep ^EESSI | sort
              echo "just run check_missing_installations.sh (should use ${{matrix.EASYSTACK_FILE}})"
              ./check_missing_installations.sh ${{matrix.EASYSTACK_FILE}}

        - name: Test check_missing_installations.sh with missing package (GCC/8.3.0)
          if: '!cancelled()'
          run: |
              source /cvmfs/pilot.nessi.no/versions/${{matrix.EESSI_VERSION}}/init/bash
              module load EasyBuild
              which eb
              eb --version
              export EESSI_PREFIX=/cvmfs/pilot.nessi.no/versions/${{matrix.EESSI_VERSION}}
              export EESSI_OS_TYPE=linux
              export EESSI_SOFTWARE_SUBDIR=${{matrix.EESSI_SOFTWARE_SUBDIR}}
              env | grep ^EESSI | sort
              # create dummy easystack file with a single entry (something that is not installed in EESSI)
              easystack_file="test.yml"
              echo "easyconfigs:" > ${easystack_file}
              echo "  - GCC-8.3.0:" >> ${easystack_file}
              echo "created easystack file '${easystack_file}' with a missing installation (GCC/8.3.0):"
              cat ${easystack_file}
              # note, check_missing_installations.sh exits 1 if a package was
              # missing, which is intepreted as false (exit code based, not
              # boolean logic), hence when the script exits 0 if no package was
              # missing it is interpreted as true, thus the test did not capture
              # the missing package
              if ./check_missing_installations.sh ${easystack_file}; then
                echo "did NOT capture missing package; test FAILED"
                exit 1
              else
                echo "captured missing package; test PASSED"
                exit 0
              fi
